#!/usr/bin/env bash
CONTROLLER=192.168.4.20
SSH_KEY=${HOME}/.ssh/id_rsa_personal
KUBECONFIG=${HOME}/pikubeconfig
KUBE_CONFIG_PATH=${HOME}/pikubeconfig
export KUBECONFIG
export KUBE_CONFIG_PATH

get_kubeconfig() {
  echo "Getting kubeconfig file from ${CONTROLLER} and writing to ${KUBECONFIG}"
  echo "Set the ENV vars KUBECONFIG and KUBE_CONFIG_PATH to use this"
  ssh -i ${SSH_KEY} pi@${CONTROLLER} sudo cat /etc/rancher/k3s/k3s.yaml | sed -e s/127.0.0.1/${CONTROLLER}/g >${KUBECONFIG}
}

help() {
  echo "usage $0 get_kubeconfig | kubectl <options> | terraform <options> "
  exit 1
}

_terraform() {
  cd terraform
  terraform $@
  cd -
}
_kubectl() {
  kubectl $@
}

CMD=${1:-}
shift || true
case ${CMD} in
get_kubeconfig) get_kubeconfig ;;
terraform) _terraform $@ ;;
kubectl) _kubectl $@ ;;
*) help ;;
esac
